import type { ExpeditionRandomEventEffectValue, ExpeditionRandomEventType } from "./expedition-types.js";

export interface ExpeditionRandomEventDefinition {
  key: string;
  type: ExpeditionRandomEventType;
  title: string;
  template: string;
  effect?: ExpeditionRandomEventEffectValue;
}

export const RANDOM_EVENT_DEFINITIONS: ExpeditionRandomEventDefinition[] = [
  {
    key: "flavor-guild-rumor",
    type: "flavor",
    title: "公会传闻",
    template: "【公会传闻】\n远征队在裂隙里发现一块牌子，上面写着“前方安全”。\n\n咪露看完沉默了三秒：\n“这地方连标点符号都不可信喵。”",
  },
  {
    key: "flavor-chest-laugh",
    type: "flavor",
    title: "宝箱发笑",
    template: "【公会速报】\n有冒险者声称自己听见宝箱在笑。\n\n目前宝箱否认了这件事，笑得更大声了。",
  },
  {
    key: "flavor-unified-escape",
    type: "flavor",
    title: "统一逃跑",
    template: "【裂隙观察】\n第 12 层出现大量脚印，方向全都朝外。\n\n咪露认真记录：\n“至少说明大家逃跑路线很统一喵。”",
  },
  {
    key: "flavor-slime-queue",
    type: "flavor",
    title: "史莱姆排队",
    template: "【公会传闻】\n今天的史莱姆开始练习排队。\n\n虽然不知道它们要排什么，但看起来很有组织。",
  },
  {
    key: "flavor-wall-message",
    type: "flavor",
    title: "墙上留言",
    template: "【远征小道消息】\n有人在墙上写下“我来过”。\n\n后面被补了一句：“然后我没了。”",
  },
  {
    key: "flavor-chest-leave",
    type: "flavor",
    title: "宝箱请假",
    template: "【公会传闻】\n今天有一个宝箱在裂隙入口贴了请假条。\n\n咪露看完点点头：\n“至少它比很多冒险者有礼貌喵。”",
  },
  {
    key: "flavor-slime-meeting",
    type: "flavor",
    title: "史莱姆开会",
    template: "【裂隙观察】\n几只史莱姆围成一圈，像是在开很严肃的会。\n\n会议结论未知，但有一只史莱姆当场鼓掌鼓散了。",
  },
  {
    key: "global-tailwind-path",
    type: "global",
    title: "顺风小路",
    effect: { survivalBpDelta: 200 },
    template: "【顺风小路】\n裂隙里突然出现一条看起来还算正经的小路。\n\n当前已报名远征者：\n生还率 +2%\n\n咪露眯起眼睛：\n“看起来安全的路，通常只是比较会演喵。”",
  },
  {
    key: "global-chest-sneeze",
    type: "global",
    title: "宝箱打喷嚏",
    effect: { dropRateBpDelta: 300 },
    template: "【宝箱打喷嚏】\n远征队附近的宝箱集体打了个喷嚏，喷出一地可疑亮片。\n\n当前已报名远征者：\n遗物掉落率 +3%\n\n咪露拿小刷子扫了扫柜台：\n“亮晶晶的东西不一定值钱，但一定会让人想捡喵。”",
  },
  {
    key: "global-rift-whisper",
    type: "global",
    title: "裂隙低语",
    effect: { advanceDelta: 1, survivalBpDelta: -200 },
    template: "【裂隙低语】\n裂隙今天特别吵，像一群人在你耳边说“再往前走一点”。\n\n当前已报名远征者：\n推进层数 +1\n生还率 -2%\n\n咪露开心地盖了个章：\n“恭喜喵，今天地图会主动骗你深入一点。”",
  },
  {
    key: "global-guild-discount",
    type: "global",
    title: "公会折扣日",
    effect: { survivalBpDelta: 100, multiplierBpDelta: 1000 },
    template: "【公会折扣日】\n补给商突然良心发现，虽然只持续了三分钟。\n\n当前已报名远征者：\n生还率 +1%\n积分倍率 +0.1\n\n咪露小声补充：\n“良心发现是限时的，坑你是长期的喵。”",
  },
  {
    key: "global-pollution-backflow",
    type: "global",
    title: "污染回潮",
    effect: { purificationBpDelta: 1000, survivalBpDelta: -200 },
    template: "【污染回潮】\n世界 Boss 在远处翻了个身，裂隙里的空气突然变黏。\n\n当前已报名远征者：\n裂隙净化值 +10%\n生还率 -2%\n\n咪露捂住鼻子：\n“坏消息是更危险了，好消息是更值钱了喵。”",
  },
  {
    key: "global-cat-lamp",
    type: "global",
    title: "猫灯照路",
    effect: { survivalBpDelta: 200 },
    template: "【猫灯照路】\n公会门口的猫形路灯突然亮得过分，把裂隙入口照出一条歪歪扭扭的小路。\n\n当前已报名远征者：\n生还率 +2%\n\n咪露叉腰：\n“看见没喵，公会设施偶尔也会认真上班。”",
  },
  {
    key: "global-chest-discount",
    type: "global",
    title: "宝箱打折",
    effect: { dropRateBpDelta: 500 },
    template: "【宝箱打折】\n裂隙里的宝箱挂上了“今日心情好”的牌子。\n\n当前已报名远征者：\n遗物掉落率 +5%\n\n咪露小声提醒：\n“心情好的宝箱也可能咬人喵，但至少咬得比较闪亮。”",
  },
  {
    key: "target-lucky-paw",
    type: "targeted",
    title: "幸运爪印",
    effect: { survivalBpDelta: 300 },
    template: "【幸运爪印】\n咪露不小心把爪印盖到了 {player} 的申请表上。\n\n{player} 今日：\n生还率 +3%\n\n咪露若无其事地把印泥藏起来：\n“这不是偏心喵，是行政事故。”",
  },
  {
    key: "target-unlucky-lot",
    type: "targeted",
    title: "倒霉签筒",
    effect: { survivalBpDelta: -300, dropRateBpDelta: 500 },
    template: "【倒霉签筒】\n{player} 在公会门口抽到一根写着“大概没事”的签。\n\n{player} 今日：\n生还率 -3%\n遗物掉落率 +5%\n\n咪露鼓掌：\n“大概没事，就是可能有事喵。”",
  },
  {
    key: "target-chest-stalker",
    type: "targeted",
    title: "宝箱盯上你了",
    effect: { dropRateBpDelta: 800 },
    template: "【宝箱盯上你了】\n有一个宝箱从早上开始一直跟着 {player}。\n\n{player} 今日：\n遗物掉落率 +8%\n死因文案优先使用离谱死因\n\n咪露认真提醒：\n“被宝箱喜欢不一定是好事喵。”",
  },
  {
    key: "target-temporary-spirit",
    type: "targeted",
    title: "临时斗志",
    effect: { advanceDelta: 2, survivalBpDelta: -300 },
    template: "【临时斗志】\n{player} 突然宣布今天要证明自己。\n在场的人都很担心。\n\n{player} 今日：\n推进层数 +2\n生还率 -3%\n\n咪露飞快翻开事故登记表：\n“证明自己之前，先证明一下保险买了没喵。”",
  },
  {
    key: "target-mysterious-tip",
    type: "targeted",
    title: "谜之小费",
    effect: { multiplierBpDelta: 2000 },
    template: "【谜之小费】\n有人往 {player} 的背包里塞了 1 枚会发光的假金币。\n\n{player} 今日：\n积分倍率 +0.2\n\n咪露把假金币举到灯下：\n“虽然是假的，但它骗怪物好像挺真喵。”",
  },
  {
    key: "target-map-stare",
    type: "targeted",
    title: "被地图盯上",
    effect: { advanceDelta: 1, survivalBpDelta: -200 },
    template: "【被地图盯上】\n{player} 的地图自己卷了起来，还在角落画了一个小箭头。\n\n{player} 今日：\n推进层数 +1\n生还率 -2%\n\n咪露把地图按住：\n“它好像很想带你去不该去的地方喵。”",
  },
  {
    key: "target-suspicious-luck",
    type: "targeted",
    title: "可疑好运",
    effect: { qualityDelta: 15 },
    template: "【可疑好运】\n{player} 在公会门口捡到一张写着“今天会出货”的纸条。\n\n{player} 今日：\n遗物品质点 +15\n\n咪露眯起眼睛：\n“这种好运通常有小字条款喵，不过先捡了再说。”",
  },
  {
    key: "tradeoff-greedy-wind",
    type: "tradeoff",
    title: "贪心风向",
    effect: { multiplierBpDelta: 2000, survivalBpDelta: -300 },
    template: "【贪心风向】\n裂隙里刮来一阵闻起来像积分的风。\n\n当前已报名远征者：\n积分倍率 +0.2\n生还率 -3%\n\n咪露深吸一口气：\n“闻到了吗喵？这是暴富和暴毙混在一起的味道。”",
  },
  {
    key: "tradeoff-weird-quiet",
    type: "tradeoff",
    title: "诡异安静",
    effect: { survivalBpDelta: 300, dropRateBpDelta: -500 },
    template: "【诡异安静】\n今天裂隙安静得过分，连惨叫声都很有礼貌。\n\n当前已报名远征者：\n生还率 +3%\n遗物掉落率 -5%\n\n咪露托着脸：\n“安全是安全了，就是有点穷喵。”",
  },
  {
    key: "tradeoff-chest-sale",
    type: "tradeoff",
    title: "宝箱大甩卖",
    effect: { dropRateBpDelta: 1000, survivalBpDelta: -400 },
    template: "【宝箱大甩卖】\n所有宝箱都贴上了“最后一天”的标签。\n没人知道它们明天会不会还在。\n\n当前已报名远征者：\n遗物掉落率 +10%\n生还率 -4%\n\n咪露兴奋地挥手：\n“快去喵！会咬人的折扣也是折扣！”",
  },
  {
    key: "tradeoff-lost-discount",
    type: "tradeoff",
    title: "迷路优惠",
    effect: { advanceDelta: -1, qualityDelta: 20 },
    template: "【迷路优惠】\n远征队集体绕了远路，但路上捡到不少乱七八糟的东西。\n\n当前已报名远征者：\n推进层数 -1\n遗物品质点 +20\n\n咪露低头记录：\n“虽然没走对路，但至少捡垃圾很专业喵。”",
  },
  {
    key: "tradeoff-paw-audit",
    type: "tradeoff",
    title: "猫爪审计",
    effect: { purificationBpDelta: 500, multiplierBpDelta: -1000 },
    template: "【猫爪审计】\n咪露突然开始检查所有申请表，发现大家的字都很可疑。\n\n当前已报名远征者：\n净化值 +5%\n积分倍率 -0.1\n\n咪露严肃地说：\n“字写得丑，罚你们多净化一点喵。”",
  },
  {
    key: "tradeoff-shiny-trap",
    type: "tradeoff",
    title: "亮晶晶陷阱",
    effect: { multiplierBpDelta: 2000, survivalBpDelta: -300 },
    template: "【亮晶晶陷阱】\n裂隙里出现一片会发光的地砖，看起来很值钱，也很不该踩。\n\n当前已报名远征者：\n积分倍率 +0.2\n生还率 -3%\n\n咪露兴奋地拍桌：\n“会发光的危险，至少拍照很好看喵。”",
  },
  {
    key: "tradeoff-rope-knot",
    type: "tradeoff",
    title: "安全绳打结",
    effect: { survivalBpDelta: 200, advanceDelta: -1 },
    template: "【安全绳打结】\n公会发放的安全绳全部打成了漂亮的蝴蝶结。\n\n当前已报名远征者：\n生还率 +2%\n推进层数 -1\n\n咪露认真解释：\n“安全是安全了喵，就是走得像被命运拽住后领口。”",
  },
  {
    key: "idle-demon-idle-raid",
    type: "idle",
    title: "魔王军摸鱼突袭",
    effect: { rewardPoints: 10 },
    template: "【魔王军摸鱼突袭】\n魔王君派了一小队士兵来偷袭城镇，结果刚好撞见事件触发时还没报名远征的昨日冒险者 {player}。\n\n咪露把扫帚往 {player} 手里一塞：\n“来都来了，守一下门喵。”\n\n{player} 稀里糊涂守住了城镇，获得 10 积分。",
  },
  {
    key: "idle-caught-idler",
    type: "idle",
    title: "闲人抓到了",
    effect: { rewardPoints: 10 },
    template: "【闲人抓到了】\n公会门口突然响起警报。咪露翻了翻名单，发现 {player} 昨天还挺勇，今天却暂时没出门。\n\n“太好了喵，闲人抓到了。”\n\n{player} 被临时按去守城，居然真守住了，奖励 10 积分。",
  },
  {
    key: "idle-gate-temp",
    type: "idle",
    title: "城门临时工",
    effect: { rewardPoints: 10 },
    template: "【城门临时工】\n魔王军的小兵在城门口探头探脑，正好被路过的 {player} 逮个正着。\n\n咪露在柜台后面鼓掌：\n“没报名也能上班喵，公会真会物尽其用。”\n\n{player} 完成临时守城任务，获得 10 积分。",
  },
  {
    key: "idle-broom-line",
    type: "idle",
    title: "扫帚防线",
    effect: { rewardPoints: 10 },
    template: "【扫帚防线】\n城镇外传来奇怪的脚步声。咪露看见 {player} 还在大厅附近晃悠，立刻递出一把扫帚。\n\n“别看了喵，今天的主角就是你。”\n\n{player} 用扫帚打退了魔王军侦察兵，获得 10 积分。",
  },
  {
    key: "idle-lost-soldier",
    type: "idle",
    title: "小兵迷路",
    effect: { rewardPoints: 10 },
    template: "【小兵迷路】\n一名魔王军士兵迷路进了公会大厅，开口就问远征报名处在哪。\n\n{player} 指了指反方向，士兵当场离开城镇。\n\n咪露认真盖章：\n“优秀的战术欺骗喵，奖励 10 积分。”",
  },
  {
    key: "idle-stay-home-hero",
    type: "idle",
    title: "没出门的大功臣",
    effect: { rewardPoints: 10 },
    template: "【没出门的大功臣】\n远征队不在城里，魔王军以为今天防守空虚。\n\n但他们忘了 {player} 今天事件触发时还没报名，正在城里晃。\n\n咪露把奖励袋推过去：\n“你看，偶尔不出门也能立功喵。”\n\n{player} 获得 10 积分。",
  },
  {
    key: "idle-anti-raid-drill",
    type: "idle",
    title: "公会反偷袭演练",
    effect: { rewardPoints: 10 },
    template: "【公会反偷袭演练】\n魔王军刚冲进街角，就被 {player} 当成公会演练道具拦了下来。\n\n咪露翻开记录本：\n“虽然你可能不是故意的，但功劳我先记上喵。”\n\n{player} 获得 10 积分。",
  },
  {
    key: "idle-door-guard",
    type: "idle",
    title: "看门有功",
    effect: { rewardPoints: 10 },
    template: "【看门有功】\n魔王军探子想混进公会大厅，被今天事件触发时还没报名的 {player} 当场拦住。\n\n咪露递上一小袋积分：\n“你看喵，不出门也会被剧情抓住。”\n\n{player} 获得 10 积分。",
  },
  {
    key: "idle-temp-recruit",
    type: "idle",
    title: "临时招募",
    effect: { rewardPoints: 10 },
    template: "【临时招募】\n城镇警铃响起，咪露环顾大厅，刚好看见 {player} 还没报名远征。\n\n“就你了喵，别躲，尾巴都看见你了。”\n\n{player} 被临时派去守街角，获得 10 积分。",
  },
];
